name: Checkout, Build, Test
on:
  push:
    branches:
      - master
  # Read-only repo token
  # No access to secrets
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  main:
    name: Main
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Build and test
        shell: powershell
        run: |
          dotnet restore
          dotnet build --no-restore
          dotnet test --no-build --verbosity normal
      - name: Save workspace
        uses: actions/upload-artifact@v2
        with:
          name: workspace
          path: .